<?php

$databaseDirectory = dirname(__DIR__) . '/Database';
$sources = array(
    'admin_login.sql',
    'counselling_date.sql',
    'notice.sql',
    'rank_details.sql',
    'college_details.sql',
    'college_login.sql',
    'candidate_details.sql',
    'candidate_reg_log_check.sql',
    'candidate_preferences.sql',
    'seat_allotments.sql',
    'closingrank.sql',
);

$output = array(
    '-- Generated by scripts/build_turso_seed.php from the retained legacy dumps.',
    '-- Apply Database/turso_schema.sql first. This seed is intended for an empty database.',
    'BEGIN;',
);

foreach ($sources as $source) {
    $contents = file_get_contents($databaseDirectory . '/' . $source);
    if ($contents === false) {
        throw new RuntimeException('Unable to read ' . $source);
    }

    if (!preg_match_all('/^INSERT INTO\b.*?;/ms', $contents, $matches)) {
        throw new RuntimeException('No seed statements found in ' . $source);
    }

    $output[] = '';
    $output[] = '-- ' . $source;
    foreach ($matches[0] as $statement) {
        $output[] = preg_replace('/^INSERT INTO/', 'INSERT OR IGNORE INTO', trim($statement));
    }
}

$output[] = '';
$output[] = '-- Correct the truncated email in the historical college-login dump.';
$output[] = "UPDATE college_login SET email='principal@seacomengineering.org' WHERE college_id=20;";
$output[] = 'COMMIT;';
$output[] = '';

$destination = $databaseDirectory . '/turso_seed.sql';
if (file_put_contents($destination, implode("\n", $output)) === false) {
    throw new RuntimeException('Unable to write ' . $destination);
}

echo 'Generated Database/turso_seed.sql' . PHP_EOL;
